spring.application.name=cvam-v2-spring
server.port=8080

# Secure Database Connection with Auto-Creation
spring.datasource.url=jdbc:mysql://localhost:3306/cvam_registry?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate ORM Engine Rules
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false